# netlify.toml
[build]
  functions = "netlify/functions"
  command = "npm install" 
  publish = "public" 

[build.environment] # <--- Asegúrate que esto esté exactamente así
  NODE_VERSION = "18" # <--- Y esto también
  # Esto asegura que Netlify use una versión específica de Node.js y npm.

[[plugins]] # <--- Asegúrate que esto esté con doble corchete
  package = "@netlify/plugin-node-bundler"

[[plugins]] # <--- Asegúrate que esto esté con doble corchete
  package = "netlify-plugin-chromium"
  [plugins.inputs] # <--- Y esto con un solo corchete
    args = ["--no-sandbox", "--disable-setuid-sandbox", "--single-process", "--disable-dev-shm-usage", "--no-zygote"]