# netlify.toml
[build]
  functions = "netlify/functions"
  command = "npm install" # Cambiado a 'npm install' para que siempre intente instalar
  publish = "public" # Tu carpeta de publicación, si aplica. Si no tienes frontend, puedes omitir o dejar vacía.

[build.environment]
  NODE_VERSION = "18" # <--- ¡CAMBIA ESTO A 18!
  # Esto asegura que Netlify use una versión específica de Node.js y npm.

[[plugins]]
  package = "@netlify/plugin-node-bundler"

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    args = ["--no-sandbox", "--disable-setuid-sandbox", "--single-process", "--disable-dev-shm-usage", "--no-zygote"]