# netlify.toml
[build]
  command = "npm run build" # O tu comando de build si tienes uno (e.g. "npm install")
  publish = "public" # Tu carpeta de publicación, si aplica. Si no tienes frontend, puedes omitir o dejar vacía.

[[plugins]]
  package = "@netlify/plugin-node-bundler"

[[plugins]]
  package = "netlify-plugin-puppeteer" # <--- ¡CAMBIA ESTO!
  [plugins.inputs]
    # Opcional: para usar una version específica de puppeteer (si la que instalamos arriba no funciona)
    # browser_version = "latest" # o una version exacta de Chromium
    # args = ["--no-sandbox", "--disable-setuid-sandbox"] # Estos son importantes para entornos serverless