# netlify.toml
[build]
  functions = "netlify/functions"
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "18" # Asegúrate de que esta línea esté aquí.

# La sección [[plugins]] para netlify-plugin-chromium YA NO DEBE ESTAR AQUÍ.