# netlify.toml
[build]
  functions = "netlify/functions"
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    chromium_version = "1090000"
    args = ["--no-sandbox", "--disable-setuid-sandbox", "--single-process", "--disable-dev-shm-usage", "--no-zygote"]