# netlify.toml
[build]
  functions = "netlify/functions"
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "18" # ¡Asegúrate de que esto esté aquí!

[[plugins]]
  package = "@netlify/plugin-node-bundler"

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]
    chromium_version = "1090000" # Versión específica de Chromium
    args = ["--no-sandbox", "--disable-setuid-sandbox", "--single-process", "--disable-dev-shm-usage", "--no-zygote"]
